variables:
  DOCKER_PULL_SECRET: pride-gitlab-docker-secret
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  CONFIG_INI: configmap

docker_build:
  image: docker:18.09
  stage: build
  services:
    - docker:18.09-dind
  script:
    - apk add --update bash gettext tzdata coreutils ca-certificates wget
    - update-ca-certificates
    - ls
    - cat Dockerfile
    - docker info
    - docker build -t $IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE
  only:
    - pride
  when: manual

kube_deploy_prod_ec:
  environment: embassy_cloud_proteomics
  extends: .kube_deploy_script

.kube_deploy_script:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - apk add --update bash gettext tzdata coreutils
    - mkdir -p ~/.kube
    - echo $KUBE_CONFIG > kubeconfig
    - base64 -d kubeconfig > ~/.kube/config
    - kubectl config get-contexts
    - kubectl create namespace $k8s_namespace || true
    - kubectl -n $k8s_namespace delete secret $DOCKER_PULL_SECRET || true
    - kubectl -n $k8s_namespace create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - envsubst < default.database.ini > database.ini
    # create configmap for first time
    - kubectl -n $k8s_namespace create configmap $CONFIG_INI --from-file=database.ini || true
    # replace configmap if it already exists
    - kubectl -n $k8s_namespace create configmap $CONFIG_INI --from-file=database.ini -o yaml --dry-run=client | kubectl replace -f -
    - envsubst < .kubernetes.yml > kubernetes.yml
    - cat kubernetes.yml
    - kubectl -n $k8s_namespace apply -f kubernetes.yml
  only:
    - pride
  when: manual
